Design doc
julianweisbord/Deep-Learning-For-Object-Recognition-on-a-Mobile-Robot pull request #11
Opened 2018-03-04 21:47 UTC by mccallm1

Only major changes to design.tex and removed extra files. Please look over changes to 3.1, 3.1.1, and 3.3.1.

2018-03-09 04:52 UTC, julianweisbord commented
Remember to add reviewers next time.

2018-03-09 05:23 UTC, julianweisbord requested changes

2018-03-09 05:23 UTC, julianweisbord commented on docs/design_document/design.tex
> +Ubuntu is the operating system used on our project to control both the intelligent agent and all computers that communicate with it. The intelligent agent's on-board OS functions like any other compu
I think this paragraph is kind of awkward. What if we changed it to something like:

Ubuntu is the operating system (OS) used on our project to control both the intelligent agent and all computers that communicate with it. The intelligent agent's on-board OS functions like any other computer, but runs ROS (Robot Operating System) which is an Open Source set of libraries that provide a series of high-level functions to help user's write software for mobile robots. The computer used to communicate with the intelligent robot must also run Ubuntu and ROS to create an effective channel for robot communication and data transfer. Programs such as Rviz, Gmapping, and Mapsaver are all used as auxilary programs to aid us in gathering our test data.

2018-03-09 05:23 UTC, julianweisbord commented on docs/design_document/design.tex
> +While ROS is not a true operating system in the same sense Linux is, the program runs constantly in the background of the intelligent agent managing everything from sensors, to motors, to inter-proce
I don't think there is a big enough relation between ROS and Linux to say this, ROS is a framewok of tools and software packages for controlling robots while Linux is a kernel which connects GUI applications to the CPU, RAM, I/O, etc.

2018-03-09 05:23 UTC, julianweisbord commented on docs/design_document/design.tex
> +ROS is also the most common operating system for robotic systems. It is open source and has BSD licensing which are two big reasons we chose it as part of our design. Being open source is one of the
RuOS?

2018-03-09 05:23 UTC, julianweisbord commented on docs/design_document/design.tex
> +ROS is also the most common operating system for robotic systems. It is open source and has BSD licensing which are two big reasons we chose it as part of our design. Being open source is one of the
Consider revising: "Two key concepts exist that stand out more than the others and that is the package and the stack."

Also maybe change: "The stack is a collection of packages that offer functionalities like navigation, positioning, mapping, and others"
to: "The stack is a collection of packages that offers functionalities like navigation, positioning, mapping, and much more"

2018-03-09 05:23 UTC, julianweisbord commented on docs/design_document/design.tex
> +We utilize ROS as our method to manipulate the fetch robots sensors, positioning, mapping, and cameras. ROS libraries provide the system with the necessary tools to map an entire room so the fetch ro
We utilize ROS as our method to manipulate the Fetch's sensors, positioning, mapping, and cameras.

2018-03-09 05:23 UTC, julianweisbord commented on docs/design_document/design.tex
>  This project uses DMA to ideally improve the agent's rate of classification over time. Without using DMA, the agent will only remember the information it learned in its last training epoch which most
Let's change DMA to Elastic Weight Consolidation (EWC)

2018-03-09 05:23 UTC, julianweisbord commented on docs/design_document/design.tex
> +There are two large systems that must be implemented to create an intelligent agent that can correctly recognize objects in its environment, these are the Data Collection phase and the Image Recognit
Change DMA to EWC here too. Also maybe write a sentence about image noise around: "For this project, the agent is trained on images from varying angles of common objects in a lab environment."

2018-03-12 18:36 UTC, julianweisbord commented
Any update to this?

2018-03-17 04:04 UTC, julianweisbord commented
We need to get these changes approved by McGrath asap.

2018-03-19 05:28 UTC, Rodrigmi commented
Have you done the changes that Julian suggested? Once those are done it should be good to go.

2018-04-14 16:28 UTC, mccallm1 commented
Document updated with suggestions in mind, should be good to approve and send out.

2018-04-14 16:29 UTC, mccallm1 reviewed
Good input: helps clarify wording and updated usage

2018-04-27 20:55 UTC, mccallm1 reviewed
Changes were added to file and PR is ready to be reviewed again

2018-05-12 00:44 UTC, julianweisbord approved these changes

2018-05-12 01:01 UTC, merged