data capture
julianweisbord/Deep-Learning-For-Object-Recognition-on-a-Mobile-Robot pull request #13
Opened 2018-03-08 05:22 UTC by Rodrigmi

Have added the minimum number files necessary to run the data capture
on the fetch robot by adding this to your catkin workspace

2018-03-09 05:35 UTC, julianweisbord requested changes
I think that all of these files should probably just go under the path: Deep-Learning-For-Object-Recognition-on-a-Mobile-Robot/src/image_capture/

Also remember to add instructions to the readme dependencies. Start with a line that says to install ROS indigo then mention the catkin workspace, changes to the .bashrc, etc.

2018-03-12 18:36 UTC, julianweisbord commented
Any update to this?

2018-03-12 18:40 UTC, Rodrigmi commented
No I haven't worked on it since Thursday because I went home for the weekend to spend time with my parents for my moms birthday.

2018-03-13 02:58 UTC, Rodrigmi commented
Just updated the dependencies in the root directory and moved the lifelong_object_learning package into image_capture.

2018-03-13 21:25 UTC, julianweisbord commented on README.md
> +Add following two lines to your .bash_rc
Add the following

2018-03-13 21:31 UTC, julianweisbord commented
Since your updating the location of data_collect.py, delete the original file at: Deep-Learning-For-Object-Recognition-on-a-Mobile-Robot/src/image_capture/data_collect.py
Can you delete the imgs folder at the root directory?
Other than that everything looks good!

2018-03-14 23:07 UTC, julianweisbord commented
Also add a "results" folder at the base of our repo and within that put a "setup" folder. We should place our setup mapping files there instead of in "Deep-Learning-For-Object-Recognition-on-a-Mobile-Robot/src/image_capture/lifelong_object_learning/mapping/"
Also remember to add your sequence of commands from one note to the readme :)

2018-03-15 04:47 UTC, Rodrigmi commented
Made the changes Julian requested, should be all good now.

2018-03-16 04:36 UTC, julianweisbord commented
.gitignore files depend on the operating system so its uncommon to push a gitignore which may need to be different from person to person, but other than that this looks great!

2018-03-16 04:36 UTC, julianweisbord submitted a review, later dismissed

2018-03-16 04:49 UTC, Rodrigmi commented
Ok I didn’t know that, should I remove it then before we merge it?

2018-03-16 04:51 UTC, julianweisbord commented
That'd be great!

2018-03-16 07:26 UTC, Rodrigmi commented
Removed the .gitignore file

2018-03-16 07:28 UTC, mccallm1 approved these changes
Initial changes to code looks nice and clean, and reworking of file structure aids the logical flow of the pipeline.

2018-03-17 04:03 UTC, merged