Image cropping
julianweisbord/Deep-Learning-For-Object-Recognition-on-a-Mobile-Robot pull request #16
Opened 2018-03-19 05:26 UTC by Rodrigmi

Added the image cropping file to prep our images for running them through our CNN.

2018-03-19 16:40 UTC, julianweisbord approved these changes
We'll have to go back and add PEP8 to this file soon but for now it looks good.

2018-03-22 04:58 UTC, julianweisbord commented
@mccallm1 can you review this PR?

2018-03-22 20:49 UTC, mccallm1 reviewed
Should probably make vars like object class non-hard coded, command line args for example

2018-03-24 20:42 UTC, julianweisbord commented
:+1: Or both via default args if no command line args are provided

2018-04-24 19:31 UTC, julianweisbord requested changes
PEP8, comments

2018-05-04 03:11 UTC, julianweisbord commented
I found this module to be difficult to use. The directory structure is too specific, and instead of creating directories to save the newly cropped images, it requires that you already have them made. More comments would also be helpful, especially regarding how the user can change the file to make the cropped images larger or smaller.

2018-05-11 05:39 UTC, julianweisbord commented on src/crop_image.py
> +#!/usr/bin/env python
Add a comment header, see https://github.com/julianweisbord/Deep-Learning-For-Object-Recognition-on-a-Mobile-Robot/blob/master/src/learning/model.py

2018-05-11 05:44 UTC, julianweisbord commented on src/crop_image.py
> +    @param image_path: The path to the image to edit
Its best if function headers should have a description, the parameters, and the return value, see https://github.com/julianweisbord/Deep-Learning-For-Object-Recognition-on-a-Mobile-Robot/blob/master/src/learning/model.py

2018-05-11 05:46 UTC, julianweisbord commented on src/crop_image.py
> +    for instance_num in range(5):
No magic numbers

2018-05-11 05:48 UTC, julianweisbord commented on src/crop_image.py
> +'''
This should be inside main and formatted like the other function headers

2018-05-11 05:49 UTC, julianweisbord commented on src/crop_image.py
> +            print("Index: ", index)  # Printing index of current current image
Make sure that comments have correct grammar and are full sentences

2018-05-11 07:37 UTC, mccallm1 requested changes
Function headers are probably the most important addition based on Ben's feedback

2018-05-11 10:20 UTC, Rodrigmi commented
The image cropping file now creates directories if they don' exist to save the cropped images. It also takes command line arguments now for a path to the data_captured folder and the image class that you want to crop.

2018-05-12 00:31 UTC, julianweisbord commented on src/crop_image.py
>  from os import listdir
I don't see the purpose importing a bunch of os functions, if you are still just going to import os

2018-05-12 00:31 UTC, julianweisbord commented on src/crop_image.py
> +    crop - Image cropping function
Function headers https://github.com/julianweisbord/Deep-Learning-For-Object-Recognition-on-a-Mobile-Robot/blob/master/src/learning/model.py

2018-05-12 00:32 UTC, julianweisbord commented on src/crop_image.py
> +    if (len(sys.argv) < 5):
No magic numbers

2018-05-12 01:11 UTC, julianweisbord submitted a review, later dismissed

2018-05-12 01:36 UTC, mccallm1 submitted a review, later dismissed

2018-05-12 01:46 UTC, julianweisbord approved these changes

2018-05-12 01:50 UTC, merged